#cloud-init
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

write_files:
  - path: /root/docker-compose.yml
    content: |
        version: '3.9'

        services:
          db:
            image: mysql
            ports:
              - "10.10.10.3:3306:3306"
            restart: always
            environment:
              - MYSQL_ROOT_PASSWORD=gitea
              - MYSQL_USER=gitea
              - MYSQL_PASSWORD=gitea
              - MYSQL_DATABASE=gitea
            volumes:
              - ./mysql:/volume
              
        volumes:
          mysql: {}

runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - systemctl start docker
  - systemctl enable docker
  - cd /root/ && docker-compose up -d
  - chmod a+w /mnt/*